
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew awscli
brew bash
brew bat
brew brotli
brew c-ares
brew ca-certificates
brew cffi
brew chezmoi
brew circleci
brew cryptography
brew dagger
brew direnv
brew fish
brew gettext
brew gh
brew git
brew icu4c@76
brew jq
brew k9s
brew krew
brew kubecolor
brew kubectx
brew kubernetes-cli
brew kustomize
brew lazygit
brew libgit2
brew libnghttp2
brew libssh2
brew libunistring
brew libuv
brew m4
brew mpdecimal
brew ncurses
brew node
brew oniguruma
brew openssl@3
brew oras
brew pcre2
brew pkgconf
brew prettier
brew pycparser
brew pyenv
brew python@3.12
brew readline
brew sqlite
brew starship
brew stow
brew terraform-docs
brew tflint
brew tree
brew uv
brew xz
brew yq

tap homebrew/cask
cask 1password
cask arc
cask docker
cask font-jetbrains-mono-nerd-font
cask ghostty
cask github
cask jetbrains-toolbox
cask microsoft-auto-update
cask microsoft-outlook
cask microsoft-teams
cask raycast
cask spotify
cask warp
cask zed

tap jozu-ai/kitops
brew kitops

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 803453959 Slack (4.41.105)
